### ISSUE TITLE
Editor Improvements

### ISSUE THREAD

**Issue by GeoffreyByrne** [slaent/issues#1]
- [x] Thread/Post Preview
- [x] Video Support
  - [x] YouTube https://github.com/slaent/issues/issues/4
  - [ ] GIFV, WEBM https://github.com/slaent/issues/issues/35
- [x] Improved Image embed
  - [ ] WebP

**Comment by hiya-tiger** [comment]
How's this issue coming along? anywhere near the next step.

**Comment by todesignandconquer** [comment]
@hiya-tiger It's coming along. I am re-factoring/re-writing large swaths of the codebase again. I am down to needing to solve one issue wrt to the new framework I am using, but once that is solved it'll be straight feature development
