### ISSUE TITLE
Android Lollipop notification bar

### ISSUE THREAD

**Issue by todesignandconquer** [slaent/issues#13]
> Any chance of adding support for Lollipop where the colour of the notification and address bar change depending on the site? For example when you visit xda they turn orange and on droid-life they turn pink. 

![image](https://cloud.githubusercontent.com/assets/5931477/8244333/6531f75a-15d4-11e5-94ca-c452e6d03ec1.png)

**Comment by Ukumio** [comment]
I believe this is done, at least that's what users on the site are reporting. Don't have Android so I can't confirm, I also can't close this :P
