### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by todesignandconquer** [slaent/issues#14]
**User Should:**
 - [x] Add a new device
 - [x] Scan a QR Code or put in a base64 encoded string manually
 - [x] Verify token before it is saved

**When the user attempts to login and they have a device present:**
 - [x] Use form wizard to take them to a device select screen after successful login
 - [x] User should verify their token
 - [x] If verified, finally log them in

**Comment by hiya-tiger** [comment]
So is this only for mods? or not for the masses?

I see it's done.
