### ISSUE TITLE
Secure certificate

### ISSUE THREAD

**Issue by pythonesque** [slaent/issues#38]
Let's wait for Mozilla's root certificate to go live.

**Comment by hiya-tiger** [comment]
now, gaf got one, so should slaent.

**Comment by todesignandconquer** [comment]
They're very expensive, but yes @hiya-tiger

**Comment by hiya-tiger** [comment]
@todesignandconquer didn't ya'll say slaent's worth a couple g's, spend dat

**Comment by todesignandconquer** [comment]
Ain't nobody giving us that money. But there's a legit open source certificate now so we can implement that.

**Comment by hiya-tiger** [comment]
@todesignandconquer cool.

**Comment by todesignandconquer** [comment]
This is done!
