### ISSUE TITLE
Can't access Control panel or post on forums!

### ISSUE THREAD

**Issue by MasterKitten117** [slaent/issues#49]
Hi,
After making my account I tried to change my avatar but after uploading the image, now it gives me "Server Error (500)" I can't even post on threads!
I made a new account but issue is still there!

**Comment by todesignandconquer** [comment]
Hey there,

Can you link me to the avatar you are trying to upload? Thanks!

**Comment by MasterKitten117** [comment]
this is the image I uploaded: https://imgur.com/VhfxU95

**Comment by todesignandconquer** [comment]
Ok thanks. I will look into it and let you know.

**Comment by todesignandconquer** [comment]
Hrmm, works for me. Are you making sure to wait for the image to upload? It takes a little bit (sometimes 30 seconds) to upload and generate the image. Don't kill the browser and have a little patience.

If that doesn't work, then I'll look into it some more.
