### ISSUE TITLE
Messages Improvements

### ISSUE THREAD

**Issue by todesignandconquer** [slaent/issues#63]
- [x] Ordering in the inbox is wrong, it should be based on the last response (bug)
- [x] Need to show who/when the last response was (enhancement, ui and ux)
- [x] Remembering last post read (enhancement)
- [x] Hitting enter on the user search box should return results (enhancement)
- [x] Ability to archive/delete message (enhancement)
  - [x] Mark message as read before it's deleted
- [x] Images overflow on mobile, need to set max-width (bug)
- [x] Remove ability to send yourself a Message
  - A sender is automatically tagged so it is redundant
  - Attempting to send yourself a message causes an IntegrityError on duplicate key
- [x] Fix spoiler highlighting
- [x] Handle Banned users
- [x] Fix line-height in forms
- [x] Move away from PM tag concept
  - [x] Messages all get inserted/updated on the cache table
  - [x] Re-Factor PM tags to be a generic User Tag

**Comment by pythonesque** [comment]
So long as we ensure that private messages are all nested at most one level deep (i.e. each thread has a single parent shared by everyone), finding the thread for a post is as simple as a single self join from the post to its parent.  Therefore, to find the most recently updated PMs, we simply need to order by descending post id, join to the parent, and use a [loose index scan](https://wiki.postgresql.org/wiki/Loose_indexscan) to get the first n distinct values efficiently (this is the same technique we should be using on the front page).
